/*

Copyright 2023-2024 Marc Ketel
SPDX-License-Identifier: Apache-2.0

*/

#ifndef RiscvEmulatorDefineCSRMachineTrapHandling_H_
#define RiscvEmulatorDefineCSRMachineTrapHandling_H_

#if (RVE_E_ZICSR == 1)
// Machine cause exception code.

#define MCAUSE_EXCEPTION_CODE_INSTRUCTION_ADDRESS_MISALIGNED 0
#define MCAUSE_EXCEPTION_CODE_INSTRUCTION_ACCESS_FAULT       1
#define MCAUSE_EXCEPTION_CODE_ILLEGAL_INSTRUCTION            2
#define MCAUSE_EXCEPTION_CODE_BREAKPOINT                     3
#define MCAUSE_EXCEPTION_CODE_LOAD_ADDRESS_MISALIGNED        4
#define MCAUSE_EXCEPTION_CODE_LOAD_ACCESS_FAULT              5
#define MCAUSE_EXCEPTION_CODE_STORE_ADDRESS_MISALIGNED       6
#define MCAUSE_EXCEPTION_CODE_STORE_ACCESS_FAULT             7
#define MCAUSE_EXCEPTION_CODE_ENVIRONMENT_CALL_FROM_UMODE    8
#define MCAUSE_EXCEPTION_CODE_ENVIRONMENT_CALL_FROM_SMODE    9
#define MCAUSE_EXCEPTION_CODE_ENVIRONMENT_CALL_FROM_MMODE    11
#define MCAUSE_EXCEPTION_CODE_INSTRUCTION_PAGE_FAULT         12
#define MCAUSE_EXCEPTION_CODE_LOAD_PAGE_FAULT                13
#define MCAUSE_EXCEPTION_CODE_STORE_PAGE_FAULT               15
#define MCAUSE_EXCEPTION_CODE_DOUBLE_TRAP                    16
#define MCAUSE_EXCEPTION_CODE_SOFTWARE_CHECK                 18
#define MCAUSE_EXCEPTION_CODE_HARDWARE_ERROR                 19

#endif

#endif